dbt_datamodeling:
  outputs:
    dev:
      dataset: raw_invoicesa
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /workspaces/online-retail-capstone/capstone/key/capstonedw1-315214a22b59.json
      location: US
      method: service-account
      priority: interactive
      project: capstonedw1
      threads: 1
      type: bigquery
  target: dev
